---
title: "PS270 Final Project"
author: "Cecilia Lees"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to gender and politics in the United States. Some ideas I had were comparing the amount of women in different levels or in different branches of government, or analyzing public opinion among various groups about women in political leadership positions. These ideas are very broad and would likely include large sets of data, but I hope to narrow them down into a more specific topic that relates to women in politics as I continue to explore what data is out there.

Research question: How do political endorsements affect female political candidates differently from male political candidates in the United States?

My hypothesis is that political endorsements are more beneficial to female political candidates in winning elections than they are to male political candidates in winning elections. I think this because previous surveys have shown that Americans tend to view women political candidates at being less competent than male candidates. Since women have to face this barrier of public perception that men don't have to deal with, I think political endorsements will go farther for women because of how it shifts public perception.

My explanatory variable is the political endorsements gained by female candidates and the political endorsements gained by male candidates. I will be looking at both political endorsements by influential figures in politics as well as political endorsements by different organizations. For my outcome variable of interest, I will look at how far these candidates made it in the race for the position they are running for. This means I will be looking at their outcomes in the primaries or in the runoff elections depending on the situation.

